//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Org_Organ> Org_Organ { get; set; }
        public DbSet<Org_OrganPerson> Org_OrganPerson { get; set; }
        public DbSet<Org_Person> Org_Person { get; set; }
        public DbSet<Sys_Attachment> Sys_Attachment { get; set; }
        public DbSet<Sys_AttachmentConver> Sys_AttachmentConver { get; set; }
        public DbSet<Sys_AttachmentSet> Sys_AttachmentSet { get; set; }
        public DbSet<Sys_BillNo> Sys_BillNo { get; set; }
        public DbSet<Sys_Function> Sys_Function { get; set; }
        public DbSet<Sys_IdentityValues> Sys_IdentityValues { get; set; }
        public DbSet<Sys_Log> Sys_Log { get; set; }
        public DbSet<Sys_Mail> Sys_Mail { get; set; }
        public DbSet<Sys_Menu> Sys_Menu { get; set; }
        public DbSet<Sys_Module> Sys_Module { get; set; }
        public DbSet<Sys_Role> Sys_Role { get; set; }
        public DbSet<Sys_RoleFunction> Sys_RoleFunction { get; set; }
        public DbSet<Sys_SysInfo> Sys_SysInfo { get; set; }
        public DbSet<Sys_UnitInfo> Sys_UnitInfo { get; set; }
        public DbSet<Sys_User> Sys_User { get; set; }
        public DbSet<Sys_UserConfig> Sys_UserConfig { get; set; }
        public DbSet<Sys_Menu_Bak> Sys_Menu_Bak { get; set; }
        public DbSet<Sys_User_Function> Sys_User_Function { get; set; }
    }
}
