//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_Organ
    {
        public string ID { get; set; }
        public string ParentID { get; set; }
        public string TypeID { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string TaxNumber { get; set; }
        public string Bank { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Path { get; set; }
        public string PathName { get; set; }
        public string SortStr { get; set; }
        public Nullable<bool> IsVirtual { get; set; }
    }
}
