//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_Person
    {
        public string PersonID { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public Nullable<int> Sex { get; set; }
        public string BirthDay { get; set; }
        public string JobPhone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string JobPhone2 { get; set; }
        public string EMail { get; set; }
        public string QQ { get; set; }
        public string MSN { get; set; }
        public string ICQ { get; set; }
        public string FamilyAddress { get; set; }
        public string PostCode { get; set; }
        public string HomeTel { get; set; }
        public Nullable<bool> DeleteMark { get; set; }
        public string AvatarPath { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> StaffFlag { get; set; }
        public string DutyType { get; set; }
        public Nullable<int> EMAIL_CAPACITY { get; set; }
        public string LimitsID { get; set; }
        public string pingying { get; set; }
    }
}
