//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Log
    {
        public int LogID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string PersonName { get; set; }
        public string IP { get; set; }
        public string LogContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> DeleteMark { get; set; }
        public string HostName { get; set; }
        public string Type { get; set; }
    }
}
