//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Sys_User
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PersonID { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public Nullable<bool> IsSuper { get; set; }
        public Nullable<bool> IsForbid { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<bool> DeleteMark { get; set; }
        public string HID { get; set; }
    }
}
