//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Module
    {
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string WebURL { get; set; }
        public Nullable<int> SysID { get; set; }
        public Nullable<int> IsTab { get; set; }
        public Nullable<bool> IsSys { get; set; }
        public Nullable<bool> DeleteMark { get; set; }
    }
}
