//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_BillNo
    {
        public string ID { get; set; }
        public string ModuleCode { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> SpaceMark { get; set; }
        public string DateFormat { get; set; }
        public Nullable<int> Length { get; set; }
        public string MaxDate { get; set; }
        public Nullable<int> MaxNum { get; set; }
        public string Creater { get; set; }
        public string CreateName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> DeleteMark { get; set; }
    }
}
