//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Menu
    {
        public int MenuID { get; set; }
        public string MenuCode { get; set; }
        public string MenuEName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> IsShow { get; set; }
        public string MenuName { get; set; }
        public string WebUrl { get; set; }
        public Nullable<int> SysID { get; set; }
        public Nullable<bool> DeleteMark { get; set; }
        public Nullable<byte> Dynamic { get; set; }
    }
}
