//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_SysInfo
    {
        public int SysID { get; set; }
        public string SysCode { get; set; }
        public string SysName { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Path { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public Nullable<bool> DeleteMark { get; set; }
        public Nullable<int> OpenModel { get; set; }
    }
}
