//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_AttachmentConver
    {
        public string AttachmentID { get; set; }
        public string ConverTo { get; set; }
        public string ConverResult { get; set; }
        public Nullable<System.DateTime> ConverTime { get; set; }
        public Nullable<decimal> UseTimes { get; set; }
    }
}
