//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UnitInfo
    {
        public string UnitID { get; set; }
        public string Name { get; set; }
        public string SortName { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string PostCode { get; set; }
        public string Address { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public string Legal { get; set; }
        public string LegalTelPhone { get; set; }
        public string Bank { get; set; }
        public string Account { get; set; }
        public string Abstruct { get; set; }
        public string AffixFile { get; set; }
        public string CorporateCode { get; set; }
        public string TaxCode { get; set; }
        public Nullable<System.DateTime> EnrollDate { get; set; }
        public string NomicRemark { get; set; }
    }
}
